image: node:14.16.0-alpine3.10

stages:
  - install
  - test
  - build

cache:
  paths:
    - node_modules/

install_deps:
  stage: install
  script: yarn install
  artifacts:
    paths:
      - node_modules/

run_e2e_tests:
  stage: test
  services:
    - postgres:alpine
  variables:
    POSTGRES_DB: $DB_NAME
    POSTGRES_USER: $DB_USER
    POSTGRES_PASSWORD: $DB_PASSWORD
    POSTGRES_HOST_AUTH_METHOD: trust

  script: yarn run test:e2e

build_app:
  stage: build
  script: yarn run tsbuild

build_docker_image:
  image: docker:stable
  stage: build
  services:
    - docker:stable-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
