services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata_test:/var/lib/postgresql/data
    networks:
      - realtapp-network
    restart: always

  api:
    environment:
      DB_HOST: db
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - realtapp-network
    build:
      context: .
      dockerfile: ./Dockerfile.test
    ports:
      - '5000:5000'
    restart: on-failure

networks:
  realtapp-network:
